feat:Added support for modal component
adobe-rnd/aem-boilerplate-forms-old pull request #142
Opened 2024-08-09 08:47 UTC by ravise5

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.page/drafts/rae/modal
- After: https://modal--aem-boilerplate-forms--adobe-rnd.hlx.page/drafts/rae/modal

2024-08-09 09:41 UTC, nit23uec commented on blocks/form/mappings.js
> +  if (properties?.modal) {
:type property should be used here.

2024-08-09 09:42 UTC, nit23uec commented on blocks/form/rules/index.js
> +    fieldWrapper.dataset.fieldModelChanged = JSON.stringify(Math.random());
whats the use if fieldModelChanged?

2024-08-09 10:04 UTC, nit23uec commented on blocks/form/components/modal/modal.js
> +      this.formModel.getElement(panel?.id).visible = false;
null check on this.formModel missing.

2024-08-14 05:14 UTC, ravise5 commented on blocks/form/rules/index.js
> +    fieldWrapper.dataset.fieldModelChanged = JSON.stringify(Math.random());
Yes @nit23uec

2024-08-21 06:09 UTC, nit23uec commented on component-definition.json
> +                  "jcr:title": "modal",
minor: `Modal`

2024-08-21 06:11 UTC, nit23uec commented on scripts/form-editor-support.js
> +              annotateContainer(dialog, fd);
pls write a unit test case for modal.

2024-08-21 06:12 UTC, ravise5 commented on scripts/form-editor-support.js
> +              annotateContainer(dialog, fd);
sure

2024-08-21 06:12 UTC, nit23uec commented on component-definition.json
> +                  "enabled": true
`visible` should be set as false here.

2024-08-21 06:13 UTC, nit23uec commented on blocks/form/rules/index.js
> +export function subscribe(fieldDiv, callback) {
pls add jsdocs over this function.

2024-08-21 06:15 UTC, nit23uec commented on blocks/form/rules/index.js
>      if (!field) {
can you pls shift the null check for field also outside the for loop?

2024-08-21 06:17 UTC, nit23uec commented on blocks/form/components/modal/modal.css
> +body.modal-open {
do we have some editor specific css also? I can't see any changes in form-editor-support.css

2024-08-21 06:18 UTC, ravise5 commented on blocks/form/components/modal/modal.css
> +body.modal-open {
Yes I missed it. Thanks!

2024-08-21 06:19 UTC, nit23uec commented on blocks/form/mappings.js
> +let customComponents = ['modal'];
I dont think we should have customComponents for this use case.

2024-08-21 06:20 UTC, nit23uec requested changes
inline comments

2024-08-21 06:24 UTC, ravise5 commented on blocks/form/mappings.js
> +let customComponents = ['modal'];
@nit23uec Then how will we identify modal?

2024-08-21 06:25 UTC, nit23uec commented on blocks/form/mappings.js
> +let customComponents = ['modal'];
`const OOTBComponentDecorators = ['file-input', 'wizard', 'modal'];
`

2024-08-21 07:06 UTC, nit23uec commented on scripts/form-editor-support.js
> +      const fieldWrapper = items[i].classList.contains('modal') ? items[i].closest('.panel-wrapper') : items[i];
this spl handling shouldn't be required. assuming the dom is like:
```
<fieldset>
  <div class=modal>
    <dialog>
      <div class=modal-content>
          <legend>
          <div>
          ..children of panel
      </div>
     </dialog>
   </div>
</fieldset>
```

2024-08-21 07:09 UTC, nit23uec commented on scripts/form-editor-support.js
> +              const { childNodes } = fieldWrapper.querySelector('.modal-content');
better to have a function `getContainerChildren(fieldWrapper, fd)`and then have modal specific logic there. it will also help in segregating customisation that may be required in editor for similar components.

2024-08-21 07:14 UTC, ravise5 commented on scripts/form-editor-support.js
> +      const fieldWrapper = items[i].classList.contains('modal') ? items[i].closest('.panel-wrapper') : items[i];
When `annotateItems ` is called from `applyChanges` for modal the item passed is div.modal. 
I'm instrumenting the fieldset only here, so I need the panelWrapper in this case. And its children under div.modal-content.

2024-08-21 07:14 UTC, nit23uec commented on blocks/form/mappings.js
> +  if (getCustomComponents().includes(type) || getOOTBComponents().includes(type)) {
I'd want to get away with the spl handling for file input and wizard above

2024-08-21 07:17 UTC, ravise5 commented on scripts/form-editor-support.js
> +      const fieldWrapper = items[i].classList.contains('modal') ? items[i].closest('.panel-wrapper') : items[i];
Yes even with this structure we need to handle it separately.
I tried using `replaceWith` as we discussed but it can only be used once html is attached to the dom so its not posssible to have the fieldset inside the dialog.

2024-08-21 07:21 UTC, ravise5 commented on blocks/form/mappings.js
> +  if (getCustomComponents().includes(type) || getOOTBComponents().includes(type)) {
Yeah, but can we do that in a separate PR as a lot of test cases would need to be fixed once this change is made.

2024-08-21 07:36 UTC, nit23uec commented on scripts/form-editor-support.js
> +      const fieldWrapper = items[i].classList.contains('modal') ? items[i].closest('.panel-wrapper') : items[i];
we need to reuse `getContainerChildren` while applying updates too.
` annotateItems(getContainerChildren(parent, parentDef), formDef, {});`
So, this spl handling wont be required.

2024-08-21 07:37 UTC, nit23uec commented on blocks/form/mappings.js
> +  if (getCustomComponents().includes(type) || getOOTBComponents().includes(type)) {
Sure.

2024-08-21 08:57 UTC, nit23uec commented on scripts/form-editor-support.js
> +function getContainerChildNodes(container, fd) {
we'd also need to call this from https://github.com/adobe-rnd/aem-boilerplate-forms/pull/142/files#diff-82002029e2e75cc923320758f76d96888dca9d1b0883250a438580fc96257f6cR307

2024-08-21 09:22 UTC, nit23uec commented on scripts/form-editor-support.js
> +  if (fd[':type'] === 'modal') {
do we still need this check?
if its for applyChanges flow, then we need not annotate the container again.

2024-08-21 09:24 UTC, nit23uec commented on blocks/form/rules/index.js
> +    fieldWrapper.dataset.fieldModelChanged = JSON.stringify(Math.random());
I don't like this hack, but don't have a better suggestion atm.

2024-08-21 09:24 UTC, ravise5 commented on scripts/form-editor-support.js
> +function getContainerChildNodes(container, fd) {
Added.

2024-08-21 09:35 UTC, ravise5 commented on scripts/form-editor-support.js
> +  if (fd[':type'] === 'modal') {
Yes this check is redundant. Removing...

2024-08-21 13:53 UTC, vdua commented on blocks/form/components/modal/modal.js
> +    dialogContent.classList.add('modal-content');
any specific reason for adding this css class ?

2024-08-21 14:03 UTC, vdua commented on blocks/form/components/modal/modal.js
> +    }, 0);
isnt there any event on which it can be done ?

2024-08-21 14:53 UTC, ravise5 commented on blocks/form/components/modal/modal.js
> +    }, 0);
Currently `showModal` is invoked when fieldset visibility changes via the subscribe method.

2024-08-21 14:55 UTC, ravise5 commented on blocks/form/components/modal/modal.js
> +    dialogContent.classList.add('modal-content');
`    setTimeout(() => {
      this.dialog.querySelector('.modal-content').scrollTop = 0;
    }, 0);`

We use this class to reset the scroll position of the main content every time show modal is invoked. No css is getting applied

2024-08-28 09:24 UTC, ravise5 commented
@nit23uec I've written a playwright test for modal, the collateral needs to use boilerplate repo so, ill add that once these changes are merged into main.

2024-09-04 16:37 UTC, nit23uec requested changes
We'd need changes in _component models and definitions as well.

2024-09-04 16:37 UTC, nit23uec commented on models/form/_modal.json
> +                    "visible": true
fd:viewType is missing

2024-09-04 16:37 UTC, nit23uec commented on component-filters.json
> +      "modal",
This should be updated in _form.json filters.

2024-09-05 06:52 UTC, ravise5 commented on component-filters.json
> +      "modal",
Done.

2024-09-05 06:54 UTC, ravise5 commented on models/form/_modal.json
> +                    "visible": true
done

2024-09-05 06:54 UTC, ravise5 commented
I've skipped pranay's failing test in my PR for now @nit23uec

2024-09-05 10:14 UTC, nit23uec approved these changes

2024-09-05 10:15 UTC, merged