test: Fix component delete function in UE
adobe-rnd/aem-boilerplate-forms-old pull request #165
Opened 2024-09-10 09:34 UTC by pranay-tippa

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://{branch}--aem-boilerplate-forms--adobe-rnd.hlx.live/

2024-09-11 06:23 UTC, nit23uec commented on test/e2e/main/page/universalEditorBasePage.js
> +      const isComponentSelected = await frame.locator(this.componentSelectorValidation(component)).isVisible();
componentSelectorValidation is coupled with text-input. this makes the code confusing to understand.
we should just have an API to get the selected component from the content tree and then decide whether it's a form or not.

2024-09-11 06:24 UTC, nit23uec commented on test/e2e/main/page/universalEditorBasePage.js
> +      if (!isComponentSelected && isAdaptiveFormSelected) {
avoid too many eslint disables. better to take out these lines as a separate func outside while

2024-09-11 06:24 UTC, nit23uec commented on test/e2e/main/page/universalEditorBasePage.js
> +        const expandButton = frame.locator(this.getExpandCollapseButton('Expand'));
lets have a common method to expand the component in the tree

2024-09-11 06:25 UTC, nit23uec commented on test/e2e/main/page/universalEditorBasePage.js
> +        expect(await frame.locator(this.componentSelectorValidation(component)).isVisible()).toBe(true);
lets have a  `isComponentSelected` method.

2024-09-11 06:26 UTC, nit23uec commented on test/e2e/main/page/universalEditorBasePage.js
>        await frame.locator(this.selectors.deleteButton).click();
common method to deleteComponent is required here.

2024-09-11 06:30 UTC, nit23uec commented
The tests code is quite unreadable at present and thus, not maintainable.
I'd suggest to consider refactoring of this code to improve its readability and maintainability.
lets have 2 classes for:
1. ComponentUtils (with `addComponent`, `deleteComponent` methods) 
2. ContentTreeUtils (with `getSelectedComponent`, `expandContainer`, `collapseContainer`, `selectComponent` methods)
and then reuse these methods from base UE test class

2024-09-11 06:31 UTC, nit23uec requested changes
requires refactoring.

2025-02-27 09:57 UTC, ravise5 commented
c

2025-02-27 09:57 UTC, closed without merging