FORMS-15342: adding recaptcha component to UI
adobe-rnd/aem-boilerplate-forms-old pull request #187
Opened 2024-10-16 08:13 UTC by lovelymandal16

This PR creates a recaptcha component in UE under adaptive forms option.
The contains unit test for enterprise recaptcha.

Fix #FORMS-15342

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://recaptchacomponent--aem-boilerplate-forms--lovelymandal16.hlx.live/

2024-10-16 11:07 UTC, nit23uec commented on blocks/form/form.js
> +function getSitePageName(path) {
this would not work for doc based forms. pls verify the flow for doc based forms also.

2024-10-16 11:08 UTC, nit23uec commented on blocks/form/form.js
> +    const config = captchaField?.properties?.['fd:captcha']?.config;
this wont work for doc based forms.

2024-10-16 11:09 UTC, nit23uec commented on blocks/form/form.js
> +function getSitePageName(path) {
better to move it to util.js

2024-10-16 11:10 UTC, nit23uec commented on models/form/_recaptcha.json
> +                            "...": "./_common.json#/basicfields"
do all the common props make sense for captcha?

2024-10-16 11:11 UTC, nit23uec commented on scripts/form-editor-support.js
> +    newFieldWrapper.setAttribute('data-aue-model', 'recaptcha-v1');
model should be `captcha` only.

2024-10-16 11:12 UTC, nit23uec commented on scripts/form-editor-support.js
> +    const newFieldWrapper = captchaFieldWrapper.cloneNode(true);
why do need to clone the node for captcha?
can;t we just add edit-mode class to the existing dom element?

2024-10-16 11:12 UTC, nit23uec commented on scripts/form-editor-support.js
> +            annotateRecaptcha(fieldWrapper, fd);
I dont think we need this code.

2024-10-16 11:12 UTC, nit23uec requested changes
comments inline

2024-10-24 06:52 UTC, lovelymandal16 commented on blocks/form/form.js
> +function getSitePageName(path) {
made some changes to fetch config for doc-based form. The working demo of recaptcha in doc-based form is posted on the scrum channel. Please have a look, and let me know your thoughts

2024-10-24 06:54 UTC, lovelymandal16 commented on blocks/form/form.js
> +    const config = captchaField?.properties?.['fd:captcha']?.config;
i Have made changes to fetch config. Debugged with doc-based form, present code seem to be working. Here is the google doc link : https://drive.google.com/drive/u/0/folders/1ogYjvnxzQn8cF5MH-7FYRIvpWQZNK-kB

2024-10-24 06:54 UTC, lovelymandal16 commented on blocks/form/form.js
> +function getSitePageName(path) {
Moved it to utils.js

2024-10-24 06:55 UTC, lovelymandal16 commented on scripts/form-editor-support.js
> +    newFieldWrapper.setAttribute('data-aue-model', 'recaptcha-v1');
Reverted changes from form-editor-support.js

2024-10-24 06:55 UTC, lovelymandal16 commented on scripts/form-editor-support.js
> +    const newFieldWrapper = captchaFieldWrapper.cloneNode(true);
Reverted all changes from form-editor-support.js

2024-10-24 06:56 UTC, lovelymandal16 commented on scripts/form-editor-support.js
> +            annotateRecaptcha(fieldWrapper, fd);
Reverted all changes from form-editor-support.js

2024-10-24 07:09 UTC, nit23uec commented
can you pls run `npm run build:json` and then commit the changes?

2024-10-24 07:10 UTC, nit23uec commented on models/form/_recaptcha.json
> +            "title": "CAPTCHA",
I think we need to have the title that's visible in the Content Tree as: `Captcha (Invisible)`

2024-10-24 07:10 UTC, nit23uec commented on models/form/_recaptcha.json
> +                    "enabled": true,
we can skip enabled and visible props here.

2024-10-24 07:11 UTC, nit23uec commented on models/form/_recaptcha.json
> +            "fields": [
we need not encapsulate the props in a container as there is only a single prop.

2024-10-24 08:47 UTC, lovelymandal16 commented on models/form/_recaptcha.json
> +                            "...": "./_common.json#/basicfields"
remote all prompts, only kept name

2024-10-28 04:27 UTC, lovelymandal16 commented on models/form/_recaptcha.json
> +            "fields": [
I tried that, but the caused issue in the rendering, as it expects an iterable. Here is a screenshot of the error. So I kept it as is.
![image](https://github.com/user-attachments/assets/11c72fdf-ddaf-4787-aa4e-6b0017ab3d03)

2024-10-28 04:27 UTC, lovelymandal16 commented on models/form/_recaptcha.json
> +                    "enabled": true,
modified

2024-10-28 04:47 UTC, nit23uec commented on models/form/_recaptcha.json
> +            "fields": [
Pls look at text or image components

2024-10-28 04:58 UTC, lovelymandal16 commented on models/form/_recaptcha.json
> +            "fields": [
_text.json and _image.json both have arrays (similar to the implementation for _recaptcha.son done here). The pre-commit hook anyway creates component-definition.json and does not have the container.

2024-10-28 05:59 UTC, nit23uec commented on models/form/_recaptcha.json
> +            "fields": [
it should not have the basic container. just the array of fields directly similar to what has been done for text and image.

2024-10-29 06:53 UTC, lovelymandal16 commented on models/form/_recaptcha.json
> +            "fields": [
removed basic container from model/properties

2024-10-29 07:17 UTC, nit23uec approved these changes

2024-11-07 08:18 UTC, merged