FORMS-14814: allow multiple file attachment
adobe-rnd/aem-boilerplate-forms-old pull request #191
Opened 2024-10-29 12:27 UTC by lovelymandal16

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://multiplefileupload--aem-boilerplate-forms--adobe-rnd.hlx.page/

2024-11-25 05:45 UTC, TalmizAhmed commented
@lovelymandal16 Could you refactor the changes to align with the new boilerplate structure?

2024-11-28 10:10 UTC, nit23uec commented on models/form/_file-input.json
> +                            "collapsible": false
min and max items are missing

2024-11-28 10:10 UTC, nit23uec requested changes
min/max items missing for multiple attach support

2024-12-10 11:04 UTC, lovelymandal16 commented on models/form/_file-input.json
> +                            "collapsible": false
Added in the recent commits

2024-12-10 15:37 UTC, nit23uec commented on models/form-components/_file-input.json
> +                        },
This msg should only come if multiple is true

2024-12-10 15:38 UTC, nit23uec commented on component-definition.json
> +          "title": "Checkbox group",
Any reason do these changes?

2024-12-10 15:39 UTC, nit23uec commented on blocks/form/form.js
> +        input.dataset.maxFilesMessage = field.properties.maxFilesMessage;
It should come in constraints msgs and not as custom props.

2024-12-10 15:40 UTC, nit23uec commented on blocks/form/form.js
> +      input.multiple = field.type === 'file[]' || field.properties?.allowMultiple;
Allow multiple check should not be required here. It should be handled via sling models.

2024-12-10 15:41 UTC, nit23uec requested changes
Inline comments

2025-02-27 09:59 UTC, ravise5 commented
new PR raised #234

2025-02-27 09:59 UTC, closed without merging