UE: Tnc Basic Tab in property rail fix
adobe-rnd/aem-boilerplate-forms-old pull request #198
Opened 2024-11-21 07:22 UTC by TalmizAhmed

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://ue-bugs--aem-boilerplate-forms--adobe-rnd.hlx.live/

2024-11-28 10:12 UTC, nit23uec commented on models/form-components/_text.json
> +              "value": "Adaptive Form Text Component."
full stop shouln't be there

2024-11-28 10:12 UTC, nit23uec commented on models/form-components/_panel.json
> +                            "component": "text",
is there a non numeric value should be entered here?

2024-11-28 10:13 UTC, nit23uec commented on models/form-components/_panel.json
> +                            "minOccur": 1
we do support minOccur = 0 in authoring. is there something I'm missing?

2024-11-28 12:14 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "minOccur": 1
We had a discussion, and @jalagari preferred 1 default value in runtime even though 0 does show up in authoring

2024-11-28 12:16 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "component": "text",
There's a bug raised to the UE team not allowing placeholder text on number fields and maxOccur needed it indicating infinite reps. Since it would look inconsistent with maxOccur, I did this for alignment.

2024-11-29 12:41 UTC, nit23uec commented on scripts/form-editor-support.js
> +window.currentMode = 'edit';
we should open a bug on UE for this if adobe-ue-edit class is not present in in first time load.
This change would annotate the form unnecessary for authoring and manipulate its markup if we open the form without UE. Further, the output of bin/franklin/delivery servlet would be impacted.

2024-11-29 12:42 UTC, nit23uec requested changes, later dismissed
check comments.

2024-11-29 12:43 UTC, nit23uec commented on models/form-components/_panel.json
> +                            "minOccur": 1
is there a reason behind the same. Have we explored:
1. the behaviour of core components
2. any technical limitations with mic occur = 0 in the runtime?

2024-12-03 10:42 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "minOccur": 1
We have a limitation in runtime with min occur = 0. 
When we have a button with a rule to add instance to a panel with minOccur = 0, it does not work.
FORMS-17543 has been logged for this issue.

2024-12-03 10:44 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "minOccur": 1
The default behaviour in core components when not having any numeric value defined the dialog is to render the panel once.

2024-12-03 10:46 UTC, TalmizAhmed commented on scripts/form-editor-support.js
> +window.currentMode = 'edit';
Reported to UE, and @pranay-tippa has verified that it has been fixed from their end. Reverting this change.

2024-12-04 17:15 UTC, jalagari commented on models/form-components/_panel.json
> +                            "component": "text",
@TalmizAhmed - Did you open jira for bug? if not please create it and track

2024-12-04 17:16 UTC, jalagari commented on models/form-components/_drop-down.json
> +              "enum": [
Can you please ensure this exists for radio, checkbox and also for wizard

2024-12-04 19:06 UTC, nit23uec commented on models/form-common/_basic-fields.json
> +                "customErrorMsg": "Name cannot start with $ and cannot contain spaces"
Name can contain spaces as per the specification. We have supported it in the ruke editor as well.

2024-12-04 19:09 UTC, nit23uec commented on models/form-components/_panel.json
> +                            "minOccur": 1
In core components, do we persist minOccur  = 1? If not,  How is the panel rendered only once there?

2024-12-04 19:11 UTC, nit23uec commented on models/form-components/_panel.json
> +                            "component": "text",
We should not change the data type of persisted value just because of a placeholder. We can alternatively show some description in number field until the bug gets fixed. If required for cuts9mer we can persist text type on project basis but not in boilerplate

2024-12-04 19:12 UTC, nit23uec commented on models/form-components/_text.json
> +              "value": "Adaptive Form Text Component"
Rather than a value here, we should have css content via pseudo selectors as it's only a view issue

2024-12-05 06:52 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "minOccur": 1
We have a default value of 1 in core components[0], but I do not see this being registered in the minOccur = 1 in crx or in the model json.
[0]: https://github.com/adobe/aem-core-forms-components/blob/c5c6b5df9d05db5252d5a899cf38aa20538c9ef3/ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_dialog/.content.xml#L172

2024-12-05 06:58 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "component": "text",
@jalagari It's part of [this ticket](https://jira.corp.adobe.com/browse/SITES-21798?focusedId=45169164&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-45169164), after discussing with UE team here: https://cq-dev.slack.com/archives/C03M9AHGK4H/p1732615239579869?thread_ts=1715084829.191409&cid=C03M9AHGK4H

2024-12-06 10:47 UTC, TalmizAhmed commented on models/form-components/_text.json
> +              "value": "Adaptive Form Text Component"
Changed to this:
<img width="1618" alt="Screenshot 2024-12-05 at 12 57 46 PM" src="https://github.com/user-attachments/assets/b4414d64-d2bb-4ab3-b669-19a5a151ce05">

2024-12-06 10:47 UTC, TalmizAhmed commented on models/form-components/_drop-down.json
> +              "enum": [
It is present for radio and checkbox group, but I don't see why would we need it for wizard?

2024-12-06 10:47 UTC, TalmizAhmed commented on models/form-components/_panel.json
> +                            "component": "text",
@nit23uec Reverted and made it a part of description.

2024-12-06 16:23 UTC, jalagari commented on models/form-components/_text.json
> +              "value": "Adaptive Form Text Component"
This experience doesn't align with AEM Sites Text block

2025-03-03 12:21 UTC, TalmizAhmed commented on models/form-components/_text.json
> +              "value": "Adaptive Form Text Component"
Sticking to just default value now

2025-03-03 14:30 UTC, jalagari approved these changes

2025-03-03 14:32 UTC, merged