feat: Support for horizontal orientation of select component options
adobe-rnd/aem-boilerplate-forms-old pull request #207
Opened 2024-12-03 07:09 UTC by TalmizAhmed

Default view:
<img width="376" alt="Screenshot 2024-12-03 at 12 37 32 PM" src="https://github.com/user-attachments/assets/9e01dd7e-87e6-48c4-8382-495394de9696">

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://select-orientation--aem-boilerplate-forms--adobe-rnd.hlx.live/

2024-12-03 08:49 UTC, ravise5 commented
@TalmizAhmed please provide URLs in PR to see the change, screenshots are not helpful.

2024-12-03 08:51 UTC, ravise5 commented on blocks/form/form.css
> +    display: flex;
should have `main .form` prefix as this could affect css of other blocks

2024-12-03 08:56 UTC, ravise5 commented on blocks/form/form.js
> +    const layout = fd.properties['afs:layout'];
Is this a custom property we have introduced for layouts? How is it done in core-components today?

2024-12-03 08:56 UTC, ravise5 requested changes, later dismissed
check comments

2024-12-03 09:22 UTC, TalmizAhmed commented on blocks/form/form.js
> +    const layout = fd.properties['afs:layout'];
This is how layout related custom properties are presented in model json for core components

2024-12-03 09:25 UTC, TalmizAhmed commented on blocks/form/form.css
> +    display: flex;
This class is to be added dynamically to components that require it and therefore does not require the prefix.
Please see: https://github.com/adobe-rnd/aem-boilerplate-forms/blob/b2135a410b3447b9c7c2ab4d568013fa48b42f68/blocks/form/form.js#L189

2024-12-03 09:27 UTC, ravise5 commented on blocks/form/form.css
> +    display: flex;
Yeah but what if someone is using the same class in a different block, your css might impact them as well if a form is included in the page.

2024-12-03 09:28 UTC, ravise5 commented on blocks/form/form.css
> +    display: flex;
Thats why we make css specific.

2024-12-03 09:33 UTC, TalmizAhmed commented on blocks/form/form.css
> +    display: flex;
One solution to that could be to prefix an AF specific name to all AF class names:
`.afb-field-group-horizontal`
@jalagari What do you think?

2024-12-03 10:57 UTC, jalagari commented on blocks/form/form.js
> +    }
Minor -Is it better to use just **horizontal** instead of **field-group-horizontal**

2024-12-03 10:59 UTC, jalagari commented on blocks/form/form.css
> +    display: flex;
@TalmizAhmed  we can go with simple class name but @ravise5 point is regarding priority order if we use **main form .form** then its more priority then classname

2024-12-03 13:39 UTC, vdua commented on blocks/form/form.js
> +    }
why not using variant or class name here as well.

2024-12-04 10:19 UTC, jalagari commented on blocks/form/form.js
> +    }
Variant are default and card with @ravise5

2024-12-04 10:19 UTC, jalagari approved these changes, later dismissed

2024-12-05 14:37 UTC, jalagari approved these changes

2024-12-05 14:38 UTC, merged