Fix thank you message on submit
adobe-rnd/aem-boilerplate-forms-old pull request #80
Opened 2024-05-30 08:11 UTC by ujjwal5

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--ujjgupta-test-repo--ujjwal5.hlx.page/content/forms/af/ujjgupta/wizard-single
- After: https://fix-reset--ujjgupta-test-repo--ujjwal5.hlx.page/content/forms/af/ujjgupta/wizard-single

2024-05-30 10:37 UTC, vdua commented on blocks/form/form.js
> +    const thankYouMessage = form.querySelector('.form-message.success-message');
I was thinking of updating the following html structure
```
<form>
<div success-message>
</div>
<div form-content>
</div>
```
WDYT @jalagari ?

2024-05-30 12:24 UTC, jalagari commented on blocks/form/form.js
> +    const thankYouMessage = form.querySelector('.form-message.success-message');
Even I was thinking of html structure but we were facing some styline issue but we revisit it again

2024-06-03 07:13 UTC, nit23uec commented
@ujjwal5, can you pls add a test case also for this?

2024-06-03 07:13 UTC, nit23uec requested changes
test case missing.

2024-06-04 11:07 UTC, ujjwal5 commented
Closing this PR in favour of https://github.com/adobe-rnd/aem-boilerplate-forms/pull/91

2024-06-04 11:07 UTC, closed without merging