FORMS-14511:Submit test for playwright
adobe-rnd/aem-boilerplate-forms-old pull request #85
Opened 2024-05-31 06:48 UTC by pranay-tippa

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://{branch}--aem-boilerplate-forms--adobe-rnd.hlx.live/

2024-05-31 11:00 UTC, deepprakash345 commented on test/e2e/x-walk/submitButton.spec.js
> +  test.only('Clicking the button should submit the form', async () => {
Do we want to have focussed tests in the project.
cc:- @jalagari

2024-05-31 11:01 UTC, deepprakash345 commented on test/e2e/x-walk/submitButton.spec.js
> +      await fillField(page, name, textInput, emailInput, numberInput, dropDown, FilePath, dataInput);
Please refactor the fillField method. 8 arguments is too much to maintain. Try to take an array of components or an object. 
This will lead to unreadable code in the future.

2024-05-31 11:02 UTC, deepprakash345 requested changes, later dismissed
Check inline comments.

2024-06-24 13:11 UTC, pranay-tippa commented on test/e2e/x-walk/submitButton.spec.js
> +      await fillField(page, name, textInput, emailInput, numberInput, dropDown, FilePath, dataInput);
Created object and refactored fillField method

2024-06-24 15:07 UTC, ravise5 commented
@pranay-tippa Can you raise this PR to the main branch?

2024-06-24 15:07 UTC, ravise5 commented on test/e2e/x-walk/submitButton.spec.js
> +      // eslint-disable-next-line no-undef,no-underscore-dangle
async is not required here.

2024-06-25 09:09 UTC, ravise5 approved these changes

2024-06-25 09:11 UTC, merged

2024-06-25 10:00 UTC, nit23uec commented
pls avoid referencing internal jiras in public space.